version: "3.8"

services:
  debug-app:
    container_name: debug-app
    build: .
    ports:
      - 15090:80
    networks:
      - public
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
networks:
  public:
    name: public
