version: "3.8"

services:
  debug-app:
    container_name: debug-app
    build: .
    ports:
      - 18090:80
    networks:
      - public
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs
networks:
  public:
    name: public
